# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/v1/grpc_stdio.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aplugin/v1/grpc_stdio.proto\x12\tplugin.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x87\x01\n\tStdioData\x12\x36\n\x07\x63hannel\x18\x01 \x01(\x0e\x32\x1c.plugin.v1.StdioData.ChannelR\x07\x63hannel\x12\x12\n\x04\x64\x61ta\x18\x02 \x01(\x0cR\x04\x64\x61ta\".\n\x07\x43hannel\x12\x0b\n\x07INVALID\x10\x00\x12\n\n\x06STDOUT\x10\x01\x12\n\n\x06STDERR\x10\x02\x32J\n\tGRPCStdio\x12=\n\x0bStreamStdio\x12\x16.google.protobuf.Empty\x1a\x14.plugin.v1.StdioData0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin.v1.grpc_stdio_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STDIODATA._serialized_start=71
  _STDIODATA._serialized_end=206
  _STDIODATA_CHANNEL._serialized_start=160
  _STDIODATA_CHANNEL._serialized_end=206
  _GRPCSTDIO._serialized_start=208
  _GRPCSTDIO._serialized_end=282
# @@protoc_insertion_point(module_scope)
